/* GENERATED by tools/build_animatic_data.py - do not edit. */
const DATA = {
 "runtime": 474.0,
 "shots": [
  {
   "id": "OPEN-01",
   "start": 0.0,
   "dur": 6.5,
   "onscreen": []
  },
  {
   "id": "OPEN-02",
   "start": 6.5,
   "dur": 4.5,
   "onscreen": [
    "YOU ENTER UNIVERSITY TO STUDY COMPUTER SCIENCE",
    "BUT ARE YOU READY FOR THE FUTURE?"
   ]
  },
  {
   "id": "S1-01",
   "start": 11.0,
   "dur": 4.5,
   "onscreen": []
  },
  {
   "id": "S1-02",
   "start": 15.5,
   "dur": 4.5,
   "onscreen": []
  },
  {
   "id": "S1-03",
   "start": 20.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S1-04",
   "start": 25.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S1-05",
   "start": 30.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S1-06",
   "start": 35.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S2-01",
   "start": 40.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S2-02",
   "start": 45.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S2-03",
   "start": 50.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S2-04",
   "start": 55.0,
   "dur": 5.0,
   "onscreen": [
    "PROGRAMMING FUNDAMENTALS",
    "DATA STRUCTURES & ALGORITHMS",
    "OBJECT-ORIENTED PROGRAMMING",
    "DATABASE SYSTEMS",
    "OPERATING SYSTEMS",
    "COMPUTER NETWORKS",
    "SOFTWARE ENGINEERING",
    "MATHEMATICS & STATISTICS",
    "THEORY OF COMPUTATION",
    "WEB TECHNOLOGIES",
    "ARTIFICIAL INTELLIGENCE",
    "MACHINE LEARNING",
    "FINAL-YEAR PROJECT"
   ]
  },
  {
   "id": "S2-05",
   "start": 60.0,
   "dur": 5.5,
   "onscreen": []
  },
  {
   "id": "S2-06",
   "start": 65.5,
   "dur": 5.5,
   "onscreen": [
    "NOT THE FINISH LINE",
    "THE STARTING POINT"
   ]
  },
  {
   "id": "S3-01",
   "start": 71.0,
   "dur": 4.5,
   "onscreen": []
  },
  {
   "id": "S3-02",
   "start": 75.5,
   "dur": 5.5,
   "onscreen": [
    "C / C++",
    "JAVA",
    "PYTHON",
    "JAVASCRIPT"
   ]
  },
  {
   "id": "S3-03",
   "start": 81.0,
   "dur": 4.5,
   "onscreen": []
  },
  {
   "id": "S3-04",
   "start": 85.5,
   "dur": 4.5,
   "onscreen": [
    "MODERN WEB",
    "CLOUD",
    "DATA",
    "AI",
    "GENERATIVE AI",
    "EMERGING COMPUTING"
   ]
  },
  {
   "id": "S3-05",
   "start": 90.0,
   "dur": 4.5,
   "onscreen": []
  },
  {
   "id": "S4-01",
   "start": 94.5,
   "dur": 4.5,
   "onscreen": []
  },
  {
   "id": "S4-02",
   "start": 99.0,
   "dur": 5.5,
   "onscreen": [
    "VARIABLES",
    "TYPES",
    "LOOPS",
    "FUNCTIONS",
    "OBJECTS",
    "RECURSION",
    "MEMORY",
    "COMPLEXITY"
   ]
  },
  {
   "id": "S4-03",
   "start": 104.5,
   "dur": 4.5,
   "onscreen": [
    "THE LANGUAGE CHANGED — THE CONCEPTS DID NOT"
   ]
  },
  {
   "id": "S4-04",
   "start": 109.0,
   "dur": 4.5,
   "onscreen": [
    "AUTOMATION",
    "DATA ANALYSIS",
    "MACHINE LEARNING",
    "ARTIFICIAL INTELLIGENCE",
    "SCIENTIFIC COMPUTING",
    "PROTOTYPING"
   ]
  },
  {
   "id": "S4-05",
   "start": 113.5,
   "dur": 4.0,
   "onscreen": [
    "LEARN CONCEPTS FIRST. LEARN LANGUAGES AS TOOLS."
   ]
  },
  {
   "id": "S5-01",
   "start": 117.5,
   "dur": 4.5,
   "onscreen": [
    "HTML / CSS / JAVASCRIPT"
   ]
  },
  {
   "id": "S5-02",
   "start": 122.0,
   "dur": 5.0,
   "onscreen": [
    "FRONT-END FRAMEWORKS",
    "APIs",
    "DATABASES"
   ]
  },
  {
   "id": "S5-03",
   "start": 127.0,
   "dur": 5.5,
   "onscreen": [
    "CLOUD",
    "MICROSERVICES",
    "CONTAINERS",
    "SERVERLESS"
   ]
  },
  {
   "id": "S5-04",
   "start": 132.5,
   "dur": 5.5,
   "onscreen": [
    "AI-POWERED APPLICATIONS"
   ]
  },
  {
   "id": "S5-05",
   "start": 138.0,
   "dur": 4.5,
   "onscreen": [
    "CAN I BUILD SOMETHING WITH IT?"
   ]
  },
  {
   "id": "S6-01",
   "start": 142.5,
   "dur": 5.0,
   "onscreen": [
    "ARTIFICIAL INTELLIGENCE"
   ]
  },
  {
   "id": "S6-02",
   "start": 147.5,
   "dur": 6.5,
   "onscreen": [
    "MACHINE LEARNING",
    "DEEP LEARNING",
    "NATURAL LANGUAGE PROCESSING",
    "COMPUTER VISION",
    "GENERATIVE AI",
    "LARGE LANGUAGE MODELS",
    "AI AGENTS",
    "ROBOTICS"
   ]
  },
  {
   "id": "S6-03",
   "start": 154.0,
   "dur": 5.0,
   "onscreen": [
    "DATA",
    "MODEL",
    "PREDICTION",
    "DECISION",
    "AUTOMATION"
   ]
  },
  {
   "id": "S6-04",
   "start": 159.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S6-05",
   "start": 164.0,
   "dur": 5.0,
   "onscreen": []
  },
  {
   "id": "S7-01",
   "start": 169.0,
   "dur": 9.0,
   "onscreen": []
  },
  {
   "id": "S7-02",
   "start": 178.0,
   "dur": 8.0,
   "onscreen": [
    "PROBABILITY"
   ]
  },
  {
   "id": "S7-03",
   "start": 186.0,
   "dur": 8.0,
   "onscreen": [
    "LINEAR ALGEBRA"
   ]
  },
  {
   "id": "S7-04",
   "start": 194.0,
   "dur": 9.0,
   "onscreen": [
    "TOOLS CAN CALCULATE",
    "YOU MUST UNDERSTAND WHAT IT MEANS"
   ]
  },
  {
   "id": "S7-05",
   "start": 203.0,
   "dur": 8.5,
   "onscreen": []
  },
  {
   "id": "S8-01",
   "start": 211.5,
   "dur": 6.5,
   "onscreen": [
    "THEORY",
    "LECTURES · TEXTBOOKS · EXAMINATIONS · DEFINITIONS · ALGORITHMS",
    "APPLICATION",
    "GIT · CODING · APIs · CLOUD · DATABASES · AI TOOLS · PROJECTS · COLLABORATION"
   ]
  },
  {
   "id": "S8-02",
   "start": 218.0,
   "dur": 6.0,
   "onscreen": []
  },
  {
   "id": "S8-03",
   "start": 224.0,
   "dur": 7.0,
   "onscreen": [
    "I UNDERSTAND IT — AND I CAN BUILD WITH IT"
   ]
  },
  {
   "id": "S8-04",
   "start": 231.0,
   "dur": 6.0,
   "onscreen": []
  },
  {
   "id": "S9-01",
   "start": 237.0,
   "dur": 6.0,
   "onscreen": []
  },
  {
   "id": "S9-02",
   "start": 243.0,
   "dur": 6.0,
   "onscreen": []
  },
  {
   "id": "S9-03",
   "start": 249.0,
   "dur": 6.5,
   "onscreen": []
  },
  {
   "id": "S9-04",
   "start": 255.5,
   "dur": 6.5,
   "onscreen": [
    "PROBLEM SOLVING",
    "PROGRAMMING",
    "COMMUNICATION",
    "CLOUD",
    "DATA",
    "AI",
    "CYBERSECURITY",
    "VERSION CONTROL",
    "SYSTEM DESIGN",
    "TEAMWORK",
    "CONTINUOUS LEARNING"
   ]
  },
  {
   "id": "S9-05",
   "start": 262.0,
   "dur": 6.5,
   "onscreen": [
    "CAN YOU USE AI WITHOUT LOSING YOUR ABILITY TO THINK?"
   ]
  },
  {
   "id": "S10-01",
   "start": 268.5,
   "dur": 7.5,
   "onscreen": []
  },
  {
   "id": "S10-02",
   "start": 276.0,
   "dur": 7.5,
   "onscreen": []
  },
  {
   "id": "S10-03",
   "start": 283.5,
   "dur": 7.5,
   "onscreen": []
  },
  {
   "id": "S10-04",
   "start": 291.0,
   "dur": 8.0,
   "onscreen": [
    "\"CAN YOU EXPLAIN THIS?\""
   ]
  },
  {
   "id": "S10-05",
   "start": 299.0,
   "dur": 7.5,
   "onscreen": [
    "UNDERSTAND",
    "ASK AI",
    "EXPERIMENT",
    "VERIFY",
    "MODIFY",
    "EXPLAIN",
    "BUILD"
   ]
  },
  {
   "id": "S10-06",
   "start": 306.5,
   "dur": 8.0,
   "onscreen": [
    "AI SHOULD ACCELERATE LEARNING — NOT REPLACE IT"
   ]
  },
  {
   "id": "S11-01",
   "start": 314.5,
   "dur": 5.5,
   "onscreen": [
    "YEAR 1",
    "PROGRAMMING · MATHEMATICS · FUNDAMENTALS"
   ]
  },
  {
   "id": "S11-02",
   "start": 320.0,
   "dur": 5.5,
   "onscreen": [
    "YEAR 2",
    "DATA STRUCTURES · DATABASES · WEB · GIT"
   ]
  },
  {
   "id": "S11-03",
   "start": 325.5,
   "dur": 5.5,
   "onscreen": [
    "YEAR 3",
    "CLOUD · AI · DATA · SPECIALISATION"
   ]
  },
  {
   "id": "S11-04",
   "start": 331.0,
   "dur": 5.5,
   "onscreen": [
    "FINAL YEAR",
    "REAL PROJECT · RESEARCH · PORTFOLIO"
   ]
  },
  {
   "id": "S11-05",
   "start": 336.5,
   "dur": 5.5,
   "onscreen": [
    "EVIDENCE OF WHAT YOU ACTUALLY KNOW"
   ]
  },
  {
   "id": "S12-01",
   "start": 342.0,
   "dur": 6.5,
   "onscreen": [
    "2010 · SMARTPHONES",
    "2015 · CLOUD",
    "2020 · AI ACCELERATION",
    "2023 · GENERATIVE AI"
   ]
  },
  {
   "id": "S12-02",
   "start": 348.5,
   "dur": 5.5,
   "onscreen": [
    "2026 · AI AGENTS & INCREASINGLY AUTONOMOUS DEVELOPMENT"
   ]
  },
  {
   "id": "S12-03",
   "start": 354.0,
   "dur": 6.0,
   "onscreen": [
    "FUTURE · UNKNOWN"
   ]
  },
  {
   "id": "S12-04",
   "start": 360.0,
   "dur": 6.5,
   "onscreen": []
  },
  {
   "id": "S13-01",
   "start": 366.5,
   "dur": 7.0,
   "onscreen": [
    "CLASSICAL COMPUTING"
   ]
  },
  {
   "id": "S13-02",
   "start": 373.5,
   "dur": 8.0,
   "onscreen": [
    "QUANTUM COMPUTING"
   ]
  },
  {
   "id": "S13-03",
   "start": 381.5,
   "dur": 7.0,
   "onscreen": []
  },
  {
   "id": "S13-04",
   "start": 388.5,
   "dur": 7.0,
   "onscreen": []
  },
  {
   "id": "S13-05",
   "start": 395.5,
   "dur": 7.0,
   "onscreen": []
  },
  {
   "id": "S13-06",
   "start": 402.5,
   "dur": 8.0,
   "onscreen": [
    "QUANTUM ALGORITHMS",
    "QUANTUM MACHINE LEARNING",
    "CRYPTOGRAPHY",
    "OPTIMISATION",
    "SIMULATION"
   ]
  },
  {
   "id": "FIN-01",
   "start": 410.5,
   "dur": 7.5,
   "onscreen": []
  },
  {
   "id": "FIN-02",
   "start": 418.0,
   "dur": 6.5,
   "onscreen": []
  },
  {
   "id": "FIN-03",
   "start": 424.5,
   "dur": 8.5,
   "onscreen": [
    "LEARN",
    "BUILD",
    "QUESTION",
    "EXPERIMENT",
    "ADAPT",
    "CREATE",
    "NEVER STOP LEARNING"
   ]
  },
  {
   "id": "FIN-04",
   "start": 433.0,
   "dur": 7.5,
   "onscreen": []
  },
  {
   "id": "FIN-05",
   "start": 440.5,
   "dur": 7.5,
   "onscreen": []
  },
  {
   "id": "FIN-06",
   "start": 448.0,
   "dur": 8.5,
   "onscreen": [
    "THE FUTURE OF COMPUTING HAS NOT BEEN WRITTEN YET"
   ]
  },
  {
   "id": "FIN-07",
   "start": 456.5,
   "dur": 6.5,
   "onscreen": []
  },
  {
   "id": "END-01",
   "start": 463.0,
   "dur": 7.0,
   "onscreen": [
    "COMPUTER SCIENCE IS NOT A DESTINATION.",
    "IT IS A LIFELONG JOURNEY."
   ]
  },
  {
   "id": "END-02",
   "start": 470.0,
   "dur": 4.0,
   "onscreen": []
  }
 ],
 "cues": [
  {
   "start": 11.0,
   "end": 14.429,
   "text": "You have entered university to study Computer Science."
  },
  {
   "start": 14.979,
   "end": 16.693,
   "text": "You may be excited."
  },
  {
   "start": 17.243,
   "end": 26.243,
   "text": "You may believe that the next three or four years will teach you everything you need to become a software engineer."
  },
  {
   "start": 26.793,
   "end": 31.507,
   "text": "But there is something you need to understand from day one."
  },
  {
   "start": 32.057,
   "end": 36.771,
   "text": "Computer Science is one of the fastest-changing fields in the world."
  },
  {
   "start": 40.0,
   "end": 43.857,
   "text": "Your university will give you something extremely valuable: foundations."
  },
  {
   "start": 44.407,
   "end": 46.121,
   "text": "You will learn programming."
  },
  {
   "start": 46.671,
   "end": 53.1,
   "text": "You will learn algorithms, databases, operating systems, networking, software engineering, mathematics and computer science theory."
  },
  {
   "start": 53.65,
   "end": 55.364,
   "text": "You will complete assignments."
  },
  {
   "start": 55.914,
   "end": 57.629,
   "text": "You will sit examinations."
  },
  {
   "start": 58.179,
   "end": 61.179,
   "text": "You will eventually complete a major project."
  },
  {
   "start": 61.729,
   "end": 65.157,
   "text": "But your degree is not the finish line."
  },
  {
   "start": 65.707,
   "end": 67.85,
   "text": "It is the starting point."
  },
  {
   "start": 71.0,
   "end": 74.429,
   "text": "Technology does not wait for your university syllabus."
  },
  {
   "start": 74.979,
   "end": 76.479,
   "text": "Programming languages evolve."
  },
  {
   "start": 77.029,
   "end": 78.529,
   "text": "Frameworks disappear."
  },
  {
   "start": 79.079,
   "end": 81.221,
   "text": "New frameworks replace old ones."
  },
  {
   "start": 81.771,
   "end": 83.271,
   "text": "Development methodologies change."
  },
  {
   "start": 83.821,
   "end": 86.821,
   "text": "Cloud computing changes how applications are built."
  },
  {
   "start": 87.371,
   "end": 91.229,
   "text": "Artificial intelligence is changing how software itself is created."
  },
  {
   "start": 94.5,
   "end": 96.214,
   "text": "Java is still important."
  },
  {
   "start": 96.764,
   "end": 101.479,
   "text": "Learning one programming language teaches you concepts that transfer to others."
  },
  {
   "start": 102.029,
   "end": 109.314,
   "text": "But do not make the mistake of believing that mastering one language means you have mastered programming."
  },
  {
   "start": 109.864,
   "end": 111.579,
   "text": "Learn programming concepts first."
  },
  {
   "start": 112.129,
   "end": 114.271,
   "text": "Then learn languages as tools."
  },
  {
   "start": 117.5,
   "end": 119.643,
   "text": "Web development is another example."
  },
  {
   "start": 120.193,
   "end": 124.907,
   "text": "Do not spend your entire university journey learning yesterday's development stack."
  },
  {
   "start": 125.457,
   "end": 126.957,
   "text": "Understand the fundamentals."
  },
  {
   "start": 127.507,
   "end": 129.007,
   "text": "But keep asking:"
  },
  {
   "start": 129.557,
   "end": 131.7,
   "text": "What is being used today?"
  },
  {
   "start": 132.25,
   "end": 134.393,
   "text": "What is becoming important tomorrow?"
  },
  {
   "start": 134.943,
   "end": 136.443,
   "text": "And most importantly:"
  },
  {
   "start": 136.993,
   "end": 139.564,
   "text": "Can I build something with it?"
  },
  {
   "start": 142.5,
   "end": 145.5,
   "text": "Artificial Intelligence is not one single technology."
  },
  {
   "start": 146.05,
   "end": 148.621,
   "text": "It is a family of technologies."
  },
  {
   "start": 149.171,
   "end": 150.671,
   "text": "Machine learning."
  },
  {
   "start": 151.221,
   "end": 152.721,
   "text": "Deep learning."
  },
  {
   "start": 153.271,
   "end": 154.771,
   "text": "Data science."
  },
  {
   "start": 155.321,
   "end": 156.821,
   "text": "Computer vision."
  },
  {
   "start": 157.371,
   "end": 158.871,
   "text": "Natural language processing."
  },
  {
   "start": 159.421,
   "end": 160.921,
   "text": "Generative AI."
  },
  {
   "start": 161.471,
   "end": 166.186,
   "text": "And increasingly, AI agents capable of using tools and performing tasks."
  },
  {
   "start": 169.0,
   "end": 172.857,
   "text": "And here is something many students discover too late."
  },
  {
   "start": 173.407,
   "end": 174.907,
   "text": "Mathematics matters."
  },
  {
   "start": 175.457,
   "end": 176.957,
   "text": "Statistics matters."
  },
  {
   "start": 177.507,
   "end": 179.007,
   "text": "Probability matters."
  },
  {
   "start": 179.557,
   "end": 181.057,
   "text": "Linear algebra matters."
  },
  {
   "start": 181.607,
   "end": 188.464,
   "text": "You may wonder why you need them when modern libraries can perform the calculations for you."
  },
  {
   "start": 189.014,
   "end": 190.729,
   "text": "The answer is simple."
  },
  {
   "start": 191.279,
   "end": 192.779,
   "text": "Tools can calculate."
  },
  {
   "start": 193.329,
   "end": 197.186,
   "text": "But you need to understand what the calculation means."
  },
  {
   "start": 197.736,
   "end": 208.45,
   "text": "If you want to move beyond simply using AI tools and start understanding AI, data science and machine learning, mathematics and statistics become powerful foundations."
  },
  {
   "start": 211.5,
   "end": 213.214,
   "text": "Do not misunderstand this."
  },
  {
   "start": 213.764,
   "end": 215.264,
   "text": "Theory is important."
  },
  {
   "start": 215.814,
   "end": 219.243,
   "text": "But theory without application can leave you unprepared."
  },
  {
   "start": 219.793,
   "end": 222.364,
   "text": "Your goal should not simply be:"
  },
  {
   "start": 222.914,
   "end": 224.629,
   "text": "'I passed the examination.'"
  },
  {
   "start": 225.179,
   "end": 226.893,
   "text": "Your goal should be:"
  },
  {
   "start": 227.443,
   "end": 233.871,
   "text": "'I understand the concept — and I can use it to solve a real problem.'"
  },
  {
   "start": 237.0,
   "end": 240.0,
   "text": "The technology industry does not simply ask:"
  },
  {
   "start": 240.55,
   "end": 242.693,
   "text": "'What subjects did you study?'"
  },
  {
   "start": 243.243,
   "end": 244.743,
   "text": "It increasingly asks:"
  },
  {
   "start": 245.293,
   "end": 247.007,
   "text": "'What can you build?'"
  },
  {
   "start": 247.557,
   "end": 249.7,
   "text": "'What problems can you solve?'"
  },
  {
   "start": 250.25,
   "end": 251.964,
   "text": "'Can you learn quickly?'"
  },
  {
   "start": 252.514,
   "end": 255.086,
   "text": "'Can you work with modern tools?'"
  },
  {
   "start": 255.636,
   "end": 258.207,
   "text": "'Can you collaborate with other people?'"
  },
  {
   "start": 258.757,
   "end": 260.257,
   "text": "And increasingly:"
  },
  {
   "start": 260.807,
   "end": 265.521,
   "text": "'Can you use AI effectively without losing your ability to think?'"
  },
  {
   "start": 268.5,
   "end": 270.643,
   "text": "Artificial intelligence creates another challenge."
  },
  {
   "start": 271.193,
   "end": 273.764,
   "text": "You can now generate an essay."
  },
  {
   "start": 274.314,
   "end": 275.814,
   "text": "Generate code."
  },
  {
   "start": 276.364,
   "end": 277.864,
   "text": "Generate diagrams."
  },
  {
   "start": 278.414,
   "end": 279.914,
   "text": "Generate explanations."
  },
  {
   "start": 280.464,
   "end": 283.036,
   "text": "Even generate an entire project structure."
  },
  {
   "start": 283.586,
   "end": 286.157,
   "text": "But there is a dangerous shortcut:"
  },
  {
   "start": 286.707,
   "end": 289.707,
   "text": "using AI without understanding what it produces."
  },
  {
   "start": 290.257,
   "end": 293.686,
   "text": "AI should accelerate learning — not replace learning."
  },
  {
   "start": 294.236,
   "end": 298.95,
   "text": "Use AI as a tutor, coding assistant, reviewer and brainstorming partner."
  },
  {
   "start": 299.5,
   "end": 303.357,
   "text": "But make sure you can explain what you submit."
  },
  {
   "start": 303.907,
   "end": 311.621,
   "text": "Otherwise, you may pass an assignment while failing to develop the skill the assignment was supposed to teach."
  },
  {
   "start": 314.5,
   "end": 319.214,
   "text": "Do not wait until your final year to build your portfolio."
  },
  {
   "start": 319.764,
   "end": 321.264,
   "text": "Start early."
  },
  {
   "start": 321.814,
   "end": 323.314,
   "text": "Build small projects."
  },
  {
   "start": 323.864,
   "end": 325.364,
   "text": "Break them."
  },
  {
   "start": 325.914,
   "end": 327.414,
   "text": "Fix them."
  },
  {
   "start": 327.964,
   "end": 329.464,
   "text": "Publish them."
  },
  {
   "start": 330.014,
   "end": 331.729,
   "text": "Document what you learned."
  },
  {
   "start": 332.279,
   "end": 338.707,
   "text": "Your GitHub repositories, projects and practical experience can become evidence of what you actually know."
  },
  {
   "start": 342.0,
   "end": 344.143,
   "text": "The uncomfortable truth is this:"
  },
  {
   "start": 344.693,
   "end": 352.407,
   "text": "The technology you learn in your first year may not be the technology you use when you graduate."
  },
  {
   "start": 352.957,
   "end": 355.1,
   "text": "And that is completely normal."
  },
  {
   "start": 355.65,
   "end": 359.507,
   "text": "Your most important skill is not memorising today's technology."
  },
  {
   "start": 360.057,
   "end": 363.486,
   "text": "It is learning how to learn tomorrow's technology."
  },
  {
   "start": 366.5,
   "end": 369.5,
   "text": "And there is another technology worth watching."
  },
  {
   "start": 370.05,
   "end": 371.55,
   "text": "Quantum computing."
  },
  {
   "start": 372.1,
   "end": 377.243,
   "text": "It is still an emerging field, and its practical impact remains uncertain."
  },
  {
   "start": 377.793,
   "end": 388.507,
   "text": "But if quantum computing reaches the level where it can solve important real-world problems at scale, it could create an entirely new chapter in computing."
  },
  {
   "start": 389.057,
   "end": 394.629,
   "text": "Perhaps one day, your final-year project will not simply be another web application."
  },
  {
   "start": 395.179,
   "end": 398.607,
   "text": "Perhaps you will explore a quantum computing problem."
  },
  {
   "start": 399.157,
   "end": 407.3,
   "text": "If the technology matures enough — and if you are prepared — you could be part of that journey."
  },
  {
   "start": 410.5,
   "end": 413.929,
   "text": "You came to university to study Computer Science."
  },
  {
   "start": 414.479,
   "end": 417.479,
   "text": "Do not leave with only a degree."
  },
  {
   "start": 418.029,
   "end": 420.6,
   "text": "Leave with the ability to learn."
  },
  {
   "start": 421.15,
   "end": 423.293,
   "text": "Leave knowing how to program."
  },
  {
   "start": 423.843,
   "end": 426.414,
   "text": "Leave knowing how to solve problems."
  },
  {
   "start": 426.964,
   "end": 429.536,
   "text": "Leave understanding mathematics, data and technology."
  },
  {
   "start": 430.086,
   "end": 431.586,
   "text": "Learn the fundamentals."
  },
  {
   "start": 432.136,
   "end": 433.636,
   "text": "Use modern tools."
  },
  {
   "start": 434.186,
   "end": 435.686,
   "text": "Experiment with AI."
  },
  {
   "start": 436.236,
   "end": 437.736,
   "text": "Build real projects."
  },
  {
   "start": 438.286,
   "end": 440.0,
   "text": "Do not fear change."
  },
  {
   "start": 440.55,
   "end": 446.979,
   "text": "Because the biggest technology you will learn at university may not be a programming language."
  },
  {
   "start": 447.529,
   "end": 450.529,
   "text": "It may be the ability to adapt."
  },
  {
   "start": 451.079,
   "end": 452.579,
   "text": "And remember:"
  },
  {
   "start": 453.129,
   "end": 456.986,
   "text": "The future of computing has not been written yet."
  },
  {
   "start": 457.536,
   "end": 460.107,
   "text": "Perhaps you will help write it."
  }
 ],
 "viz": {
  "OPEN-01": [
   "canopy",
   0
  ],
  "OPEN-02": [
   "gate",
   0
  ],
  "S1-01": [
   "gate",
   1
  ],
  "S1-02": [
   "gate",
   2
  ],
  "S1-03": [
   "corridor",
   0
  ],
  "S1-04": [
   "desk",
   0
  ],
  "S1-05": [
   "corridor",
   1
  ],
  "S1-06": [
   "desk",
   1
  ],
  "S2-01": [
   "corridor",
   2
  ],
  "S2-02": [
   "desk",
   2
  ],
  "S2-03": [
   "corridor",
   3
  ],
  "S2-04": [
   "columns",
   0
  ],
  "S2-05": [
   "desk",
   3
  ],
  "S2-06": [
   "doorway",
   0
  ],
  "S3-01": [
   "rail",
   0
  ],
  "S3-02": [
   "rail",
   1
  ],
  "S3-03": [
   "rail",
   2
  ],
  "S3-04": [
   "rail",
   3
  ],
  "S3-05": [
   "rail",
   4
  ],
  "S4-01": [
   "desk",
   4
  ],
  "S4-02": [
   "solids",
   0
  ],
  "S4-03": [
   "solids",
   1
  ],
  "S4-04": [
   "panels",
   0
  ],
  "S4-05": [
   "solids",
   2
  ],
  "S5-01": [
   "unfold",
   0
  ],
  "S5-02": [
   "unfold",
   1
  ],
  "S5-03": [
   "unfold",
   2
  ],
  "S5-04": [
   "unfold",
   3
  ],
  "S5-05": [
   "unfold",
   4
  ],
  "S6-01": [
   "aitree",
   0
  ],
  "S6-02": [
   "aitree",
   1
  ],
  "S6-03": [
   "pipeline",
   0
  ],
  "S6-04": [
   "aitree",
   2
  ],
  "S6-05": [
   "aitree",
   3
  ],
  "S7-01": [
   "mathfield",
   0
  ],
  "S7-02": [
   "mathfield",
   1
  ],
  "S7-03": [
   "mathfield",
   2
  ],
  "S7-04": [
   "mathfield",
   3
  ],
  "S7-05": [
   "mathfield",
   4
  ],
  "S8-01": [
   "paths",
   0
  ],
  "S8-02": [
   "paths",
   1
  ],
  "S8-03": [
   "paths",
   2
  ],
  "S8-04": [
   "paths",
   3
  ],
  "S9-01": [
   "globe",
   0
  ],
  "S9-02": [
   "globe",
   1
  ],
  "S9-03": [
   "panels",
   1
  ],
  "S9-04": [
   "globe",
   2
  ],
  "S9-05": [
   "globe",
   3
  ],
  "S10-01": [
   "fracture",
   0
  ],
  "S10-02": [
   "fracture",
   1
  ],
  "S10-03": [
   "fracture",
   2
  ],
  "S10-04": [
   "fracture",
   3
  ],
  "S10-05": [
   "chain",
   0
  ],
  "S10-06": [
   "chain",
   1
  ],
  "S11-01": [
   "tower",
   0
  ],
  "S11-02": [
   "tower",
   1
  ],
  "S11-03": [
   "tower",
   2
  ],
  "S11-04": [
   "tower",
   3
  ],
  "S11-05": [
   "tower",
   4
  ],
  "S12-01": [
   "rail",
   5
  ],
  "S12-02": [
   "rail",
   6
  ],
  "S12-03": [
   "rail",
   7
  ],
  "S12-04": [
   "rail",
   8
  ],
  "S13-01": [
   "qubit",
   0
  ],
  "S13-02": [
   "qubit",
   1
  ],
  "S13-03": [
   "qubit",
   2
  ],
  "S13-04": [
   "qubit",
   3
  ],
  "S13-05": [
   "qubit",
   4
  ],
  "S13-06": [
   "panels",
   2
  ],
  "FIN-01": [
   "gate",
   3
  ],
  "FIN-02": [
   "horizon",
   0
  ],
  "FIN-03": [
   "horizon",
   1,
   "sequence"
  ],
  "FIN-04": [
   "horizon",
   2
  ],
  "FIN-05": [
   "horizon",
   3
  ],
  "FIN-06": [
   "horizon",
   4
  ],
  "FIN-07": [
   "horizon",
   5
  ],
  "END-01": [
   "endcard",
   0
  ],
  "END-02": [
   "endcard",
   1
  ]
 }
};
