#!/usr/bin/env python3
"""Emit animatic/data.js — the flattened shot list, narration cues and viz map."""

from __future__ import annotations

import json
import os

from timeline_lib import ROOT, SENTENCE_PAUSE, WORDS_PER_SECOND, all_shots, load

MIN_LINE_SECONDS = 1.5


def main() -> None:
    data, scenes = load()

    with open(os.path.join(ROOT, "production", "animatic_viz.json")) as fh:
        viz = json.load(fh)["shots"]

    shots = []
    for shot in all_shots(scenes):
        if shot.id not in viz:
            raise SystemExit(f"shot {shot.id} has no animatic_viz.json entry")
        shots.append({
            "id": shot.id,
            "start": round(shot.start, 3),
            "dur": round(shot.dur, 3),
            "onscreen": shot.onscreen,
        })

    cues = []
    for scene in scenes:
        clock = scene.start
        for lineno, line in enumerate(scene.vo):
            dur = max(len(line.split()) / WORDS_PER_SECOND, MIN_LINE_SECONDS)
            cues.append({
                "start": round(clock, 3),
                "end": round(clock + dur, 3),
                "text": line,
            })
            clock += dur + SENTENCE_PAUSE
        # A scene must never overrun its own picture time.
        if scene.vo and clock - SENTENCE_PAUSE > scene.end + 0.01:
            raise SystemExit(f"scene {scene.id} narration overruns its shots")

    payload = {
        "runtime": round(sum(s["dur"] for s in shots), 3),
        "shots": shots,
        "cues": cues,
        "viz": viz,
    }

    out = os.path.join(ROOT, "animatic", "data.js")
    with open(out, "w") as fh:
        fh.write("/* GENERATED by tools/build_animatic_data.py - do not edit. */\n")
        fh.write("const DATA = ")
        json.dump(payload, fh, indent=1, ensure_ascii=False)
        fh.write(";\n")

    print(f"wrote animatic/data.js — {len(shots)} shots, {len(cues)} cues, "
          f"{payload['runtime']:.1f}s")


if __name__ == "__main__":
    main()
